[2024-11-17T19:16:07.336+0000] {processor.py:186} INFO - Started process (PID=37) to work on /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:16:07.337+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/sample_aws_connection.py for tasks to queue
[2024-11-17T19:16:07.339+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:16:07.339+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:16:07.348+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:16:07.346+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/sample_aws_connection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sample_aws_connection.py", line 6, in <module>
    from airflow.operators import BashOperator, S3KeySensor
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/__init__.py)
[2024-11-17T19:16:07.350+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:16:07.369+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/sample_aws_connection.py took 0.037 seconds
[2024-11-17T19:16:38.068+0000] {processor.py:186} INFO - Started process (PID=51) to work on /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:16:38.070+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/sample_aws_connection.py for tasks to queue
[2024-11-17T19:16:38.073+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:16:38.072+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:16:38.081+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:16:38.079+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/sample_aws_connection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sample_aws_connection.py", line 6, in <module>
    from airflow.operators import BashOperator, S3KeySensor
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/__init__.py)
[2024-11-17T19:16:38.082+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:16:38.098+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/sample_aws_connection.py took 0.038 seconds
[2024-11-17T19:17:08.767+0000] {processor.py:186} INFO - Started process (PID=60) to work on /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:17:08.768+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/sample_aws_connection.py for tasks to queue
[2024-11-17T19:17:08.771+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:17:08.770+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:17:08.776+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:17:08.774+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/sample_aws_connection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sample_aws_connection.py", line 6, in <module>
    from airflow.operators import BashOperator, S3KeySensor
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/__init__.py)
[2024-11-17T19:17:08.777+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:17:08.794+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/sample_aws_connection.py took 0.034 seconds
[2024-11-17T19:17:39.418+0000] {processor.py:186} INFO - Started process (PID=69) to work on /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:17:39.420+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/sample_aws_connection.py for tasks to queue
[2024-11-17T19:17:39.421+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:17:39.421+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:17:39.427+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:17:39.425+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/sample_aws_connection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sample_aws_connection.py", line 6, in <module>
    from airflow.operators import BashOperator, S3KeySensor
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/__init__.py)
[2024-11-17T19:17:39.428+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:17:39.447+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/sample_aws_connection.py took 0.035 seconds
[2024-11-17T19:18:10.127+0000] {processor.py:186} INFO - Started process (PID=77) to work on /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:18:10.128+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/sample_aws_connection.py for tasks to queue
[2024-11-17T19:18:10.129+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:18:10.129+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:18:10.135+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:18:10.132+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/sample_aws_connection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sample_aws_connection.py", line 6, in <module>
    from airflow.operators import BashOperator, S3KeySensor
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/__init__.py)
[2024-11-17T19:18:10.136+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:18:10.251+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/sample_aws_connection.py took 0.127 seconds
[2024-11-17T19:18:40.692+0000] {processor.py:186} INFO - Started process (PID=86) to work on /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:18:40.693+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/sample_aws_connection.py for tasks to queue
[2024-11-17T19:18:40.694+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:18:40.694+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:18:40.698+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:18:40.697+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/sample_aws_connection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sample_aws_connection.py", line 6, in <module>
    from airflow.operators import BashOperator, S3KeySensor
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/__init__.py)
[2024-11-17T19:18:40.699+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:18:40.719+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/sample_aws_connection.py took 0.030 seconds
[2024-11-17T19:19:00.120+0000] {processor.py:186} INFO - Started process (PID=89) to work on /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:19:00.121+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/sample_aws_connection.py for tasks to queue
[2024-11-17T19:19:00.123+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:19:00.123+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:19:00.130+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:19:00.128+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/sample_aws_connection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sample_aws_connection.py", line 6, in <module>
    from airflow.operators import BashOperator, S3KeySensor
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/__init__.py)
[2024-11-17T19:19:00.131+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:19:00.149+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/sample_aws_connection.py took 0.035 seconds
[2024-11-17T19:19:20.345+0000] {processor.py:186} INFO - Started process (PID=98) to work on /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:19:20.346+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/sample_aws_connection.py for tasks to queue
[2024-11-17T19:19:20.350+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:19:20.349+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:19:20.354+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:19:20.353+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/sample_aws_connection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sample_aws_connection.py", line 7
    from 
         ^
SyntaxError: invalid syntax
[2024-11-17T19:19:20.355+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:19:20.371+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/sample_aws_connection.py took 0.033 seconds
[2024-11-17T19:19:39.528+0000] {processor.py:186} INFO - Started process (PID=105) to work on /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:19:39.529+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/sample_aws_connection.py for tasks to queue
[2024-11-17T19:19:39.532+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:19:39.532+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:19:39.544+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:19:39.542+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/sample_aws_connection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sample_aws_connection.py", line 7, in <module>
    from airflow.hooks import S3Hook
ImportError: cannot import name 'S3Hook' from 'airflow.hooks' (/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/__init__.py)
[2024-11-17T19:19:39.544+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:19:39.560+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/sample_aws_connection.py took 0.040 seconds
[2024-11-17T19:20:09.863+0000] {processor.py:186} INFO - Started process (PID=114) to work on /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:20:09.864+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/sample_aws_connection.py for tasks to queue
[2024-11-17T19:20:09.867+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:20:09.867+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:20:09.875+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:20:09.873+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/sample_aws_connection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sample_aws_connection.py", line 7, in <module>
    from airflow.hooks import S3Hook
ImportError: cannot import name 'S3Hook' from 'airflow.hooks' (/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/__init__.py)
[2024-11-17T19:20:09.875+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:20:09.893+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/sample_aws_connection.py took 0.038 seconds
[2024-11-17T19:20:40.403+0000] {processor.py:186} INFO - Started process (PID=123) to work on /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:20:40.405+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/sample_aws_connection.py for tasks to queue
[2024-11-17T19:20:40.408+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:20:40.407+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:20:40.413+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:20:40.411+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/sample_aws_connection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sample_aws_connection.py", line 7, in <module>
    from airflow.hooks import S3Hook
ImportError: cannot import name 'S3Hook' from 'airflow.hooks' (/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/__init__.py)
[2024-11-17T19:20:40.413+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:20:40.431+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/sample_aws_connection.py took 0.036 seconds
[2024-11-17T19:20:53.563+0000] {processor.py:186} INFO - Started process (PID=126) to work on /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:20:53.564+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/sample_aws_connection.py for tasks to queue
[2024-11-17T19:20:53.567+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:20:53.566+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:20:53.570+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:20:53.569+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/sample_aws_connection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sample_aws_connection.py", line 14
    )
     ^
SyntaxError: expected ':'
[2024-11-17T19:20:53.571+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:20:53.586+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/sample_aws_connection.py took 0.030 seconds
[2024-11-17T19:21:10.756+0000] {processor.py:186} INFO - Started process (PID=133) to work on /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:21:10.757+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/sample_aws_connection.py for tasks to queue
[2024-11-17T19:21:10.759+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:21:10.758+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:21:10.763+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:21:10.762+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/sample_aws_connection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sample_aws_connection.py", line 14
    )
     ^
SyntaxError: expected ':'
[2024-11-17T19:21:10.764+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:21:10.782+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/sample_aws_connection.py took 0.035 seconds
[2024-11-17T19:21:41.058+0000] {processor.py:186} INFO - Started process (PID=142) to work on /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:21:41.059+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/sample_aws_connection.py for tasks to queue
[2024-11-17T19:21:41.061+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:21:41.061+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:21:41.066+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:21:41.065+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/sample_aws_connection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sample_aws_connection.py", line 14
    )
     ^
SyntaxError: expected ':'
[2024-11-17T19:21:41.067+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:21:41.083+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/sample_aws_connection.py took 0.033 seconds
[2024-11-17T19:22:11.359+0000] {processor.py:186} INFO - Started process (PID=151) to work on /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:22:11.360+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/sample_aws_connection.py for tasks to queue
[2024-11-17T19:22:11.362+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:22:11.362+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:22:11.366+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:22:11.365+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/sample_aws_connection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sample_aws_connection.py", line 14
    )
     ^
SyntaxError: expected ':'
[2024-11-17T19:22:11.367+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:22:11.383+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/sample_aws_connection.py took 0.031 seconds
[2024-11-17T19:22:41.620+0000] {processor.py:186} INFO - Started process (PID=160) to work on /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:22:41.621+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/sample_aws_connection.py for tasks to queue
[2024-11-17T19:22:41.623+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:22:41.623+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:22:41.628+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:22:41.626+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/sample_aws_connection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sample_aws_connection.py", line 14
    )
     ^
SyntaxError: expected ':'
[2024-11-17T19:22:41.628+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:22:41.643+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/sample_aws_connection.py took 0.029 seconds
[2024-11-17T19:23:11.902+0000] {processor.py:186} INFO - Started process (PID=169) to work on /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:23:11.904+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/sample_aws_connection.py for tasks to queue
[2024-11-17T19:23:11.906+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:23:11.906+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:23:11.910+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:23:11.909+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/sample_aws_connection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sample_aws_connection.py", line 14
    )
     ^
SyntaxError: expected ':'
[2024-11-17T19:23:11.911+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:23:11.926+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/sample_aws_connection.py took 0.032 seconds
[2024-11-17T19:23:22.032+0000] {processor.py:186} INFO - Started process (PID=172) to work on /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:23:22.033+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/sample_aws_connection.py for tasks to queue
[2024-11-17T19:23:22.035+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:23:22.034+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:23:22.042+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:23:22.041+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/sample_aws_connection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sample_aws_connection.py", line 7, in <module>
    from airflow.hooks import S3Hook
ImportError: cannot import name 'S3Hook' from 'airflow.hooks' (/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/__init__.py)
[2024-11-17T19:23:22.043+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:23:22.060+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/sample_aws_connection.py took 0.035 seconds
[2024-11-17T19:23:45.260+0000] {processor.py:186} INFO - Started process (PID=181) to work on /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:23:45.261+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/sample_aws_connection.py for tasks to queue
[2024-11-17T19:23:45.263+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:23:45.262+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:23:45.266+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:23:45.266+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/sample_aws_connection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sample_aws_connection.py", line 22
    'bucket_name'
                ^
SyntaxError: ':' expected after dictionary key
[2024-11-17T19:23:45.267+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:23:45.286+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/sample_aws_connection.py took 0.033 seconds
[2024-11-17T19:24:13.531+0000] {processor.py:186} INFO - Started process (PID=188) to work on /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:24:13.531+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/sample_aws_connection.py for tasks to queue
[2024-11-17T19:24:13.534+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:24:13.534+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:24:13.541+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:24:13.540+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/sample_aws_connection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sample_aws_connection.py", line 7, in <module>
    from airflow.hooks import S3Hook
ImportError: cannot import name 'S3Hook' from 'airflow.hooks' (/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/__init__.py)
[2024-11-17T19:24:13.542+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:24:13.558+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/sample_aws_connection.py took 0.034 seconds
[2024-11-17T19:24:37.810+0000] {processor.py:186} INFO - Started process (PID=191) to work on /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:24:37.812+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/sample_aws_connection.py for tasks to queue
[2024-11-17T19:24:37.815+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:24:37.815+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:24:37.822+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:24:37.820+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/sample_aws_connection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sample_aws_connection.py", line 16
    def upload(filename=filename, key=key, )
                                            ^
SyntaxError: expected ':'
[2024-11-17T19:24:37.823+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:24:37.842+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/sample_aws_connection.py took 0.039 seconds
[2024-11-17T19:25:08.121+0000] {processor.py:186} INFO - Started process (PID=200) to work on /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:25:08.122+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/sample_aws_connection.py for tasks to queue
[2024-11-17T19:25:08.124+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:25:08.124+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:25:08.130+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:25:08.129+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/sample_aws_connection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sample_aws_connection.py", line 16
    def upload(filename=filename, key=key, )
                                            ^
SyntaxError: expected ':'
[2024-11-17T19:25:08.131+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:25:08.146+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/sample_aws_connection.py took 0.033 seconds
[2024-11-17T19:25:27.319+0000] {processor.py:186} INFO - Started process (PID=209) to work on /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:25:27.320+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/sample_aws_connection.py for tasks to queue
[2024-11-17T19:25:27.322+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:25:27.321+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:25:27.329+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:25:27.327+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/sample_aws_connection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sample_aws_connection.py", line 7, in <module>
    from airflow.hooks import S3Hook
ImportError: cannot import name 'S3Hook' from 'airflow.hooks' (/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/__init__.py)
[2024-11-17T19:25:27.329+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:25:27.347+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/sample_aws_connection.py took 0.032 seconds
[2024-11-17T19:25:57.846+0000] {processor.py:186} INFO - Started process (PID=217) to work on /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:25:57.847+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/sample_aws_connection.py for tasks to queue
[2024-11-17T19:25:57.850+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:25:57.849+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:25:57.855+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:25:57.854+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/sample_aws_connection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sample_aws_connection.py", line 7, in <module>
    from airflow.hooks import S3Hook
ImportError: cannot import name 'S3Hook' from 'airflow.hooks' (/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/__init__.py)
[2024-11-17T19:25:57.856+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:25:57.871+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/sample_aws_connection.py took 0.032 seconds
[2024-11-17T19:26:28.403+0000] {processor.py:186} INFO - Started process (PID=226) to work on /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:26:28.404+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/sample_aws_connection.py for tasks to queue
[2024-11-17T19:26:28.406+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:26:28.406+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:26:28.410+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:26:28.409+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/sample_aws_connection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sample_aws_connection.py", line 7, in <module>
    from airflow.hooks import S3Hook
ImportError: cannot import name 'S3Hook' from 'airflow.hooks' (/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/__init__.py)
[2024-11-17T19:26:28.411+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:26:28.425+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/sample_aws_connection.py took 0.028 seconds
[2024-11-17T19:26:58.716+0000] {processor.py:186} INFO - Started process (PID=235) to work on /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:26:58.717+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/sample_aws_connection.py for tasks to queue
[2024-11-17T19:26:58.720+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:26:58.720+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:26:58.726+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:26:58.724+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/sample_aws_connection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sample_aws_connection.py", line 7, in <module>
    from airflow.hooks import S3Hook
ImportError: cannot import name 'S3Hook' from 'airflow.hooks' (/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/__init__.py)
[2024-11-17T19:26:58.727+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:26:58.742+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/sample_aws_connection.py took 0.033 seconds
[2024-11-17T19:27:28.986+0000] {processor.py:186} INFO - Started process (PID=244) to work on /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:27:28.986+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/sample_aws_connection.py for tasks to queue
[2024-11-17T19:27:28.988+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:27:28.988+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:27:28.991+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:27:28.990+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/sample_aws_connection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sample_aws_connection.py", line 7, in <module>
    from airflow.hooks import S3Hook
ImportError: cannot import name 'S3Hook' from 'airflow.hooks' (/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/__init__.py)
[2024-11-17T19:27:28.992+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:27:29.015+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/sample_aws_connection.py took 0.034 seconds
[2024-11-17T19:27:34.028+0000] {processor.py:186} INFO - Started process (PID=245) to work on /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:27:34.028+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/sample_aws_connection.py for tasks to queue
[2024-11-17T19:27:34.030+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:27:34.030+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:27:34.275+0000] {processor.py:925} INFO - DAG(s) 's3_conn_dag' retrieved from /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:27:34.390+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:27:34.389+0000] {override.py:1911} INFO - Created Permission View: can read on DAG:s3_conn_dag
[2024-11-17T19:27:34.396+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:27:34.396+0000] {override.py:1911} INFO - Created Permission View: can edit on DAG:s3_conn_dag
[2024-11-17T19:27:34.398+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:27:34.398+0000] {override.py:1911} INFO - Created Permission View: can delete on DAG:s3_conn_dag
[2024-11-17T19:27:34.401+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:27:34.401+0000] {override.py:1911} INFO - Created Permission View: menu access on DAG Run:s3_conn_dag
[2024-11-17T19:27:34.403+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:27:34.403+0000] {override.py:1911} INFO - Created Permission View: can read on DAG Run:s3_conn_dag
[2024-11-17T19:27:34.405+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:27:34.405+0000] {override.py:1911} INFO - Created Permission View: can delete on DAG Run:s3_conn_dag
[2024-11-17T19:27:34.407+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:27:34.407+0000] {override.py:1911} INFO - Created Permission View: can create on DAG Run:s3_conn_dag
[2024-11-17T19:27:34.407+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:27:34.407+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-11-17T19:27:34.414+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:27:34.414+0000] {dag.py:3262} INFO - Creating ORM DAG for s3_conn_dag
[2024-11-17T19:27:34.418+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:27:34.418+0000] {dag.py:4180} INFO - Setting next_dagrun for s3_conn_dag to 2024-11-01 00:00:00+00:00, run_after=2024-11-01 00:00:00+00:00
[2024-11-17T19:27:34.426+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/sample_aws_connection.py took 0.402 seconds
[2024-11-17T19:28:04.559+0000] {processor.py:186} INFO - Started process (PID=254) to work on /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:28:04.560+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/sample_aws_connection.py for tasks to queue
[2024-11-17T19:28:04.563+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:28:04.563+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:28:04.650+0000] {processor.py:925} INFO - DAG(s) 's3_conn_dag' retrieved from /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:28:04.665+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:28:04.665+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-11-17T19:28:04.679+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:28:04.679+0000] {dag.py:4180} INFO - Setting next_dagrun for s3_conn_dag to 2024-11-01 00:00:00+00:00, run_after=2024-11-01 00:00:00+00:00
[2024-11-17T19:28:04.689+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/sample_aws_connection.py took 0.138 seconds
[2024-11-17T19:28:35.077+0000] {processor.py:186} INFO - Started process (PID=267) to work on /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:28:35.078+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/sample_aws_connection.py for tasks to queue
[2024-11-17T19:28:35.082+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:28:35.081+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:28:35.214+0000] {processor.py:925} INFO - DAG(s) 's3_conn_dag' retrieved from /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:28:35.230+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:28:35.230+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-11-17T19:28:35.245+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:28:35.245+0000] {dag.py:4180} INFO - Setting next_dagrun for s3_conn_dag to None, run_after=None
[2024-11-17T19:28:35.253+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/sample_aws_connection.py took 0.187 seconds
[2024-11-17T19:29:05.622+0000] {processor.py:186} INFO - Started process (PID=276) to work on /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:29:05.623+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/sample_aws_connection.py for tasks to queue
[2024-11-17T19:29:05.626+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:29:05.626+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:29:05.697+0000] {processor.py:925} INFO - DAG(s) 's3_conn_dag' retrieved from /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:29:05.710+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:29:05.710+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-11-17T19:29:05.722+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:29:05.721+0000] {dag.py:4180} INFO - Setting next_dagrun for s3_conn_dag to None, run_after=None
[2024-11-17T19:29:05.729+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/sample_aws_connection.py took 0.114 seconds
[2024-11-17T19:29:26.924+0000] {processor.py:186} INFO - Started process (PID=285) to work on /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:29:26.925+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/sample_aws_connection.py for tasks to queue
[2024-11-17T19:29:26.927+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:29:26.927+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:29:26.999+0000] {processor.py:925} INFO - DAG(s) 's3_conn_dag' retrieved from /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:29:27.052+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:29:27.052+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-11-17T19:29:27.060+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:29:27.060+0000] {dag.py:4180} INFO - Setting next_dagrun for s3_conn_dag to None, run_after=None
[2024-11-17T19:29:27.067+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/sample_aws_connection.py took 0.148 seconds
[2024-11-17T19:29:50.319+0000] {processor.py:186} INFO - Started process (PID=294) to work on /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:29:50.321+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/sample_aws_connection.py for tasks to queue
[2024-11-17T19:29:50.323+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:29:50.323+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:29:50.400+0000] {processor.py:925} INFO - DAG(s) 's3_conn_dag' retrieved from /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:29:50.409+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:29:50.409+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-11-17T19:29:50.420+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:29:50.419+0000] {dag.py:4180} INFO - Setting next_dagrun for s3_conn_dag to None, run_after=None
[2024-11-17T19:29:50.429+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/sample_aws_connection.py took 0.115 seconds
[2024-11-17T19:30:20.704+0000] {processor.py:186} INFO - Started process (PID=303) to work on /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:30:20.706+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/sample_aws_connection.py for tasks to queue
[2024-11-17T19:30:20.709+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:30:20.708+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:30:20.789+0000] {processor.py:925} INFO - DAG(s) 's3_conn_dag' retrieved from /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:30:20.816+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:30:20.816+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-11-17T19:30:20.833+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:30:20.833+0000] {dag.py:4180} INFO - Setting next_dagrun for s3_conn_dag to None, run_after=None
[2024-11-17T19:30:20.841+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/sample_aws_connection.py took 0.144 seconds
[2024-11-17T19:30:51.156+0000] {processor.py:186} INFO - Started process (PID=312) to work on /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:30:51.158+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/sample_aws_connection.py for tasks to queue
[2024-11-17T19:30:51.160+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:30:51.160+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:30:51.236+0000] {processor.py:925} INFO - DAG(s) 's3_conn_dag' retrieved from /opt/airflow/dags/sample_aws_connection.py
[2024-11-17T19:30:51.249+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:30:51.248+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-11-17T19:30:51.258+0000] {logging_mixin.py:190} INFO - [2024-11-17T19:30:51.258+0000] {dag.py:4180} INFO - Setting next_dagrun for s3_conn_dag to None, run_after=None
[2024-11-17T19:30:51.268+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/sample_aws_connection.py took 0.119 seconds
